# docker pull jupyter/all-spark-notebook
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html?highlight=root

version: "3.7"
services:
  pyspark:
    image: jupyter/all-spark-notebook:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    networks:
    - pyspark-net
    working_dir: /home/jovyan/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: jovyan
      NB_GROUP: staff
    user: root
    volumes:
    - ./work:/home/jovyan/work
    - ./.jupyter:/home/jovyan/.jupyter
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: demo
    ports:
    - "5432:5432/tcp"
    networks:
    - pyspark-net
    volumes:
    - ./pg-data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
    - "8080:8080/tcp"
    networks:
    - pyspark-net

networks:
  pyspark-net: